version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  
  # Maintain dependencies for Robot Framework
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    allow:
      # Allow only direct updates for
      # Django and any packages starting "django"
      - dependency-name: "ROBOT_FRAMEWORK_*"
        dependency-type: "direct"