version: "3.9"

services:
  robot:
    build:
      context: .
      dockerfile: Dockerfile
    image: rf-docker
    container_name: rf-docker
    shm_size: "256M"
    stdin_open: True
    tty: True
    restart: "always"
    volumes:
      - $PWD:/opt/robotframework
    command: "/bin/bash"
    networks:
      - robot-net

networks:
  robot-net:
